### ISSUE TITLE
Ajax call require some update

### ISSUE THREAD

**Issue by purnendudash** [liliapro/moodle-local_wsmanager#3]
https://github.com/liliapro/moodle-local_wsmanager/blob/726afc2c04a5918c22ce423325b00f6d64abea4a/amd/src/base.js#L36

Would request you to update the Ajax call using the latest documentation - https://moodledev.io/docs/guides/javascript/ajax

**Comment by liliapro** [comment]
That was a huge job to rewrite to a new AJAX, as i see that is since Moodle 3.9, i added postfix **_mdl39** for my JS files. Im preparing to rewrite to Moodle 3.5+ (php 7+) in future. Not now

https://github.com/liliapro/moodle-local_wsmanager/blob/eb19dfede7eda99d9284f726bf3f9a08da6e821e/amd/src/base_mdl39.js#L24
